from typing import Any, Callable, Optional, TypeVar

T = TypeVar("T")

class Typer:
    def __init__(self, name: Optional[str] = None, help: Optional[str] = None, add_completion: bool = True) -> None: ...

    def command(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

    def run(self, *args: Any, **kwargs: Any) -> None: ...


def prompt(*args: Any, **kwargs: Any) -> str: ...

def exit(code: int = 0) -> None: ...
