from typing import Any

class Align:
    def __init__(self, renderable: Any, align: str = "left", width: int = 0) -> None: ...

    def __enter__(self) -> "Align": ...

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
