from typing import Any

class Layout:
    def __init__(self, name: str = "", size: int = 0, ratio: int = 1) -> None: ...

    def split_column(self, *args: Any, **kwargs: Any) -> None: ...

    def split_row(self, *args: Any, **kwargs: Any) -> None: ...

    def update(self, *args: Any, **kwargs: Any) -> None: ...
