from typing import Any

class Live:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def __enter__(self) -> "Live": ...

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

    def update(self, *args: Any, **kwargs: Any) -> None: ...
